### ISSUE TITLE
How to execute on MacOS?

### ISSUE THREAD

**Issue by Tylast** [benguild/iTunesSanityCheckForMissingRatings-php#1]
OK, I assumed I could just run the script in terminal.  All I get is the script contents displayed in the terminal.  How do I execute this on the 2 XMLs I have?

**Comment by benguild** [comment]
I just tweaked the `README.md` file to have better markup, let me know if you still can't figure it out: https://github.com/benguild/iTunesSanityCheckForMissingRatings-php/blob/master/README.md

**Comment by Tylast** [comment]
All is good - it worked on 80% of my missing ratings.  "My" issue was that I tried to"download as" instead of using the github download button.  Lesson learned - don't do that.  Cheers!
